<html>
    <head>
        <title>@yield('title')</title>
    </head>
    <body>
        <div>
            @yield('header')
            <h1>@yield('title')</h1>
            <hr>
        </div>
        <div>
            @yield('content')
        </div>
        <div>
            <hr>
            @yield('footer')
            <p>&copy;Copyright All Rights Reserved.</p>
        </div>
    </body>
</html>